### PR TITLE
Bugs in the buggy function are fixed and decription is updated

### PR DESCRIPTION
**Pull request by ignotur**

### CODE REVIEW

**Comment by AlexGolovin** [comment]
I am going to review this

**Review by AlexGolovin — APPROVED** [review]

**Comment by eteq** [comment]
Thanks for opening the pull request and for the review(s)! Below I have provided a few comments about the *process* of the pull request and review. Note that we are not conducting a review of the code itself, because the exercise was about the overall process not the details of the code. Also, because there are pending suggestions, we will not merge this PR until the end of Astro Hack Week.

@ignotur - your PR has no description.  A description is useful to give additional context for potential reviewers or maintainers, so you should always fill it out unless it's literally a copy of whatever is in the title.

@AlexGolovin - while just approving is OK, it's often useful to leave an actual comment, along the lines of "I looked through all this and it all looked perfect, so I'm accepting." "Human" interactions like that are often just as important as the mechanics of "approving", both for you as a contributor and maintainers of open source packages or collaborators in a science context.

**Comment by eteq** [comment]
While the review has been completed, there's now a conflict with the original copy, probably due to a PR getting merged before this one.  @ignotur, would you like to try resolving the conflict (usually best done with `git rebase`)? If you are interested, give it a try, or if you are interested but don't know how, feel free to come look for me, @astrofrog or @bsipocz in person later on in the week.

**Comment by bsipocz** [comment]
As a closure to AstroHackWeek, we would go ahead and merge this now. However PR #9 introduced a conflict that could be resolved with the rebased mentioned above, so I go ahead and close this one instead. 
Thank you both.

**Pull request closed without merging**
